CLASS zrap100_bp_traveltp_200 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zrap100_r_traveltp_200 .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZRAP100_BP_TRAVELTP_200 IMPLEMENTATION.
ENDCLASS.
